# Generated by Django 2.1 on 2018-08-06 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('espetaculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poltrona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeracao', models.PositiveIntegerField(default=0)),
                ('espetaculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espetaculos.Espetaculo')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poltrona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poltronas.Poltrona')),
            ],
        ),
    ]
