# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-09 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estepaculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('data', models.DateTimeField(verbose_name='Data')),
            ],
        ),
        migrations.CreateModel(
            name='Poltrona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocupada', models.BooleanField(default=False)),
                ('espetaculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espetaculo.Estepaculo')),
            ],
        ),
    ]
