# Generated by Django 2.0.2 on 2018-02-02 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='espetaculo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='app.Espetaculo'),
            preserve_default=False,
        ),
    ]
