# Generated by Django 2.2.2 on 2019-06-07 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poltronas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poltronas',
            name='status',
        ),
    ]
