<a href="<?php echo $this->url('admin-event', ['action' => 'add']); ?>" class="btn btn-success">Novo evento</a>
<br/>
<br/>
<table width="100%" class="table table-striped table-bordered table-hover">
    <thead>
    <tr>
        <th>#</th>
        <th>Evento</th>
        <th>Local</th>
        <th>Capacidade</th>
        <th>Data do evento</th>
        <th>Ações</th>
    </tr>
    </thead>
    <tbody>
    <?php /** @var \Application\Entity\Event $event */
    foreach ($this->collection as $event): ?>
        <tr>
            <td><?php echo $event->getId(); ?></td>
            <td>
                <?php echo $event->getName(); ?>
                <br/>
                <small><?php echo $event->getDescription(); ?></small>
            </td>
            <td><?php echo $event->getLocation(); ?></td>
            <td><?php echo $event->getCapacity(); ?></td>
            <td><?php echo $event->getShowDate()->format('d/m/Y H:i'); ?></td>
            <td>
                <a href="<?php echo $this->url('admin-event', ['action' => 'edit', 'id' => $event->getId()]); ?>"
                   class="btn btn-default btn-sm">
                    Editar
                </a>&nbsp;
                <a href="#" rel="<?php echo $event->getId(); ?>"
                   class="btn btn-danger btn-sm btn-icon icon-left delete-link">
                    Remover
                </a>

                <div style="display: none;">
                    <form
                            action="<?php echo $this->url('admin-event', ['action' => 'delete', 'id' => $event->getId()], true) ?>"
                            method="post">
                        <input type="submit" id="delete-<?php echo $event->getId(); ?>"
                               class="btn btn-danger btn-sm btn-icon icon-left" value="Delete">
                    </form>
                </div>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>