# Generated by Django 2.0.1 on 2018-01-15 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entertainment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('start_date', models.DateTimeField(verbose_name='Data de Início')),
                ('end_date', models.DateTimeField(verbose_name='Data de Termino')),
            ],
            options={
                'verbose_name': 'Espetáculo',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5, verbose_name='Número')),
                ('value', models.FloatField(default=23.76, verbose_name='Valor')),
                ('reserve', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Poltrona',
            },
        ),
        migrations.AddField(
            model_name='entertainment',
            name='seats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Seat', verbose_name='Assentos'),
        ),
    ]
