# Generated by Django 2.0.1 on 2018-01-15 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entertainment',
            name='seats',
        ),
        migrations.AddField(
            model_name='seat',
            name='entertainments',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='core.Entertainment', verbose_name='Espetáculo'),
            preserve_default=False,
        ),
    ]
