# Generated by Django 2.0.1 on 2018-01-15 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180115_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='reserve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Reserva'),
        ),
    ]
