# Generated by Django 2.0.1 on 2018-01-16 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180115_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
            ],
            options={
                'verbose_name': 'Reserva',
                'permissions': (('read_item', 'Can read item'),),
                'proxy': True,
                'indexes': [],
            },
            bases=('core.seat',),
        ),
    ]
