# Generated by Django 2.0.1 on 2018-01-16 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_reserve'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserve',
            options={'verbose_name': 'Reserva'},
        ),
    ]
