# Generated by Django 2.1 on 2018-08-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Espetaculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('total_de_poltronas', models.PositiveIntegerField(default=20)),
            ],
        ),
    ]
