# Generated by Django 2.2.2 on 2019-06-07 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('espetaculos', '0001_initial'),
        ('poltronas', '0002_remove_poltronas_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espetaculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espetaculos.Espetaculos')),
                ('poltrona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poltronas.Poltronas')),
            ],
        ),
    ]
