<div class="col-lg-12">
    <div class="col-lg-8 seats">
        <h2>Mapa de poltronas</h2>
        <?php
        $seatsCollection = $this->event->getSeats();
        $selectedSeats = [];
        $classByStatus = [
            \Application\Entity\Seat::PRE_BOOKING => 'pre-reserved',
            \Application\Entity\Seat::CONFIRMED_RESERVATION => 'unavailable'
        ];

        /** @var \Application\Entity\Seat $seat */
        foreach ($seatsCollection as $seat) {
            $selectedSeats[$seat->getSeatNumber()] = [
                'class' => $classByStatus[$seat->getStatus()],
                'tooltip' => $seat->getCustomerEmail()
            ];
        }
        ?>
        <?php for ($i = 1; $i <= $this->event->getCapacity(); $i++) : ?>
            <?php
            $complementClass = '';
            if (array_key_exists($i, $selectedSeats)) {
                $complementClass = $selectedSeats[$i]['class'] . ' unclickable';
            } ?>
            <div class="seat <?php echo $complementClass; ?>" id="seat-<?php echo $i; ?>">&nbsp;<?php echo str_pad($i, 3, '0', STR_PAD_LEFT); ?>&nbsp;
            </div>
        <?php endfor; ?>
        <br clear="all"/>
        <hr>
        <h5>Legenda</h5>
        <span class="your-choice">Sua escolha</span>&nbsp;
        <span class="pre-reserved">Pré reserva</span>&nbsp;
        <span class="just-selected">Recém selecionada</span>&nbsp;
        <span class="unavailable">Reservada</span>
        <br clear="all"/>
        <br />
    </div>
    <div class="col-xs-6 col-md-4 event-details">
        <h3><?php echo $this->event->getName(); ?></h3>
        <br/>
        Local: <?php echo $this->event->getLocation(); ?>
        <br/>
        Capacidade: <?php echo $this->event->getCapacity(); ?> expectadores
        <br/>
        Data: <?php echo $this->event->getShowDate()->format('d/m/Y H:i'); ?>
        <hr>
        <h4>Sua escolha</h4>
        <div class="seats-selected"></div>
        <hr>
        <label>Seu e-mail</label>
        <input type="email" placeholder="Email" id="email" class="form-control">
        <br/>
        <input type="hidden" id="eventId" value="<?php echo $this->event->getId(); ?>">
        <a href="#" class="btn btn-success" id="btn-action">Reservar</a>
    </div>
</div>
<br clear="all"/>
